name: Deploy Icons

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout icons repository
        uses: actions/checkout@v2
        with:
          repository: arshnoor1411/icons-for-template
          ref: main
          path: icons

      - name: Copy icons to target repository
        run: |
          cp -t $GITHUB_WORKSPACE icons/*.png 

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update icons"
          git push
